baseURL = 'https://blog.shelchin.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'
enableRobotsTXT =true

[params]
title = "I'm Shelchin"
author = "Shelchin"
description = "Call me Shelchin"
profilePicture = "images/profile.jpg"
contentratio = 0.8
readMore = true
rssFullContent = true
mainSections = []
 
[params.umami]
serverURL = "us.umami.is"
id = "52fe77a1-0dfb-48af-89f4-eef4310b4732"
trackerScriptName = "script.js"

[params.giscus]
repo = "shelchin2023/shelchin-blog"
repoID = "R_kgDOK0trBA"
category = "General"
categoryID = "DIC_kwDOK0trBM4CbcMm"
mapping = "title"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/atshelchin"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/shelchin2023"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:hi@shelchin.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"